# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NumeroCapa
                                 A QGIS plugin
 Plugin que muestra el nùmero de capas en la tabla de contenido
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-12
        copyright            : (C) 2024 by Frank Stiven Muñoz Duitama/Universidad Distrital
        email                : fsmunozd@correo.udistrital.edu.co
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NumeroCapa class from file NumeroCapa.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .count_layers import NumeroCapa
    return NumeroCapa(iface)
